-- ERETZ Propiedades: atomic and auditable safe merge for Pipeline A.
-- Additive only. No existing property row is modified by this migration.

BEGIN;

CREATE TABLE IF NOT EXISTS public.property_merge_audit (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    property_id     bigint REFERENCES public.propiedades(id) ON DELETE SET NULL,
    source_id       text NOT NULL,
    run_id          text NOT NULL,
    field           text NOT NULL,
    old_value       jsonb,
    new_value       jsonb,
    decision        text NOT NULL CHECK (
        decision = ANY (ARRAY[
            'ACCEPTED_INSERT',
            'ACCEPTED_IMPROVEMENT',
            'ACCEPTED_SOURCE_CHANGE',
            'REJECTED_NULL_DEGRADATION',
            'REJECTED_PLACEHOLDER',
            'REJECTED_LOWER_CONFIDENCE',
            'REJECTED_AMBIGUOUS_IDENTITY',
            'REJECTED_CROSS_PROPERTY_CONTAMINATION',
            'UNCHANGED_EQUAL'
        ]::text[])
    ),
    confidence      numeric(4,3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
    reason          text NOT NULL,
    event_key       text NOT NULL,
    created_at      timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.property_merge_audit ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.property_merge_audit FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT ON public.property_merge_audit TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.property_merge_audit_id_seq TO service_role;

-- Supports property history and run reconciliation.  The table starts empty,
-- so transactional index creation is bounded and does not block propiedades.
CREATE INDEX IF NOT EXISTS idx_property_merge_audit_property_created
    ON public.property_merge_audit(property_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_property_merge_audit_run
    ON public.property_merge_audit(run_id, id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_property_merge_audit_event_key
    ON public.property_merge_audit(event_key);

CREATE OR REPLACE FUNCTION public.record_property_merge_audit(
    p_property_id bigint,
    p_source_id text,
    p_run_id text,
    p_audit jsonb
) RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
    inserted_count integer := 0;
BEGIN
    IF COALESCE(btrim(p_source_id), '') = ''
       OR COALESCE(btrim(p_run_id), '') = ''
       OR jsonb_typeof(COALESCE(p_audit, '[]'::jsonb)) <> 'array'
    THEN
        RAISE EXCEPTION 'invalid merge audit envelope';
    END IF;

    INSERT INTO public.property_merge_audit (
        property_id, source_id, run_id, field, old_value, new_value,
        decision, confidence, reason, event_key
    )
    SELECT
        p_property_id,
        p_source_id,
        p_run_id,
        entry->>'field',
        NULLIF(entry->'old_value', 'null'::jsonb),
        NULLIF(entry->'new_value', 'null'::jsonb),
        entry->>'decision',
        (entry->>'confidence')::numeric,
        entry->>'reason',
        md5(concat_ws(
            '|',
            p_run_id,
            COALESCE(p_property_id::text, ''),
            entry->>'field',
            COALESCE((entry->'old_value')::text, ''),
            COALESCE((entry->'new_value')::text, ''),
            entry->>'decision'
        ))
    FROM jsonb_array_elements(p_audit) AS entry
    ON CONFLICT (event_key) DO NOTHING;

    GET DIAGNOSTICS inserted_count = ROW_COUNT;
    RETURN inserted_count;
END
$function$;

CREATE OR REPLACE FUNCTION public.insert_property_safe(
    p_payload jsonb,
    p_source_id text,
    p_run_id text,
    p_audit jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
    inserted_id bigint;
    forbidden_keys text[];
BEGIN
    SELECT array_agg(key ORDER BY key)
    INTO forbidden_keys
    FROM jsonb_object_keys(COALESCE(p_payload, '{}'::jsonb)) AS key
    WHERE key <> ALL (ARRAY[
        'inmobiliaria_id', 'url', 'url_normalizada', 'hash_dedup',
        'titulo', 'descripcion', 'precio', 'moneda', 'tipo_propiedad',
        'operacion', 'ambientes', 'dormitorios', 'banos',
        'superficie_total', 'direccion', 'barrio', 'ciudad',
        'latitud', 'longitud', 'imagenes', 'fuente_extraccion', 'estado'
    ]::text[]);

    IF forbidden_keys IS NOT NULL THEN
        RAISE EXCEPTION 'forbidden insert keys: %', forbidden_keys;
    END IF;
    IF COALESCE((p_payload->>'inmobiliaria_id')::bigint, 0) <= 0
       OR p_source_id !~ '^[0-9]+$'
       OR p_source_id::bigint IS DISTINCT FROM (p_payload->>'inmobiliaria_id')::bigint
       OR COALESCE(btrim(p_payload->>'url'), '') = ''
       OR COALESCE(btrim(p_payload->>'url_normalizada'), '') = ''
       OR COALESCE(btrim(p_payload->>'hash_dedup'), '') = ''
       OR COALESCE(btrim(p_source_id), '') = ''
       OR COALESCE(btrim(p_run_id), '') = ''
    THEN
        RAISE EXCEPTION 'safe insert requires complete identity and audit envelope';
    END IF;

    INSERT INTO public.propiedades (
        inmobiliaria_id, url, url_normalizada, hash_dedup,
        titulo, descripcion, precio, moneda, tipo_propiedad, operacion,
        ambientes, dormitorios, banos, superficie_total,
        direccion, barrio, ciudad, latitud, longitud, imagenes,
        fuente_extraccion, estado
    ) VALUES (
        (p_payload->>'inmobiliaria_id')::integer,
        p_payload->>'url',
        p_payload->>'url_normalizada',
        p_payload->>'hash_dedup',
        p_payload->>'titulo',
        p_payload->>'descripcion',
        (p_payload->>'precio')::numeric,
        p_payload->>'moneda',
        p_payload->>'tipo_propiedad',
        p_payload->>'operacion',
        (p_payload->>'ambientes')::integer,
        (p_payload->>'dormitorios')::integer,
        (p_payload->>'banos')::integer,
        (p_payload->>'superficie_total')::numeric,
        p_payload->>'direccion',
        p_payload->>'barrio',
        p_payload->>'ciudad',
        (p_payload->>'latitud')::double precision,
        (p_payload->>'longitud')::double precision,
        CASE
            WHEN jsonb_typeof(p_payload->'imagenes') = 'array'
            THEN ARRAY(SELECT jsonb_array_elements_text(p_payload->'imagenes'))
            ELSE NULL
        END,
        p_payload->>'fuente_extraccion',
        COALESCE(NULLIF(p_payload->>'estado', ''), 'activa')
    )
    RETURNING id INTO inserted_id;

    PERFORM public.record_property_merge_audit(
        inserted_id, p_source_id, p_run_id, p_audit
    );

    RETURN jsonb_build_object(
        'status', 'inserted',
        'property_id', inserted_id,
        'audit_rows', jsonb_array_length(COALESCE(p_audit, '[]'::jsonb))
    );
END
$function$;

CREATE OR REPLACE FUNCTION public.apply_property_safe_merge(
    p_property_id bigint,
    p_inmobiliaria_id bigint,
    p_expected_url text,
    p_expected_hash_dedup text,
    p_expected_fuente_extraccion text,
    p_patch jsonb,
    p_source_id text,
    p_run_id text,
    p_audit jsonb
) RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
DECLARE
    current_row public.propiedades%ROWTYPE;
    forbidden_keys text[];
    changed_fields integer := 0;
    audit_rows integer := 0;
BEGIN
    SELECT *
    INTO current_row
    FROM public.propiedades
    WHERE id = p_property_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION 'property not found';
    END IF;
    IF current_row.inmobiliaria_id IS DISTINCT FROM p_inmobiliaria_id::integer
       OR p_source_id !~ '^[0-9]+$'
       OR p_source_id::bigint IS DISTINCT FROM p_inmobiliaria_id
       OR current_row.url IS DISTINCT FROM p_expected_url
       OR current_row.hash_dedup IS DISTINCT FROM p_expected_hash_dedup
       OR current_row.fuente_extraccion IS DISTINCT FROM p_expected_fuente_extraccion
    THEN
        RAISE EXCEPTION 'property identity changed before merge';
    END IF;

    SELECT array_agg(key ORDER BY key)
    INTO forbidden_keys
    FROM jsonb_object_keys(COALESCE(p_patch, '{}'::jsonb)) AS key
    WHERE key <> ALL (ARRAY[
        'titulo', 'descripcion', 'precio', 'moneda', 'tipo_propiedad',
        'operacion', 'ambientes', 'dormitorios', 'banos',
        'superficie_total', 'direccion', 'barrio', 'ciudad',
        'latitud', 'longitud', 'imagenes'
    ]::text[]);

    IF forbidden_keys IS NOT NULL THEN
        RAISE EXCEPTION 'forbidden merge keys: %', forbidden_keys;
    END IF;
    IF EXISTS (
        SELECT 1 FROM jsonb_each(COALESCE(p_patch, '{}'::jsonb))
        WHERE value = 'null'::jsonb
    ) THEN
        RAISE EXCEPTION 'merge patch cannot contain JSON null';
    END IF;

    SELECT count(*)::integer
    INTO changed_fields
    FROM jsonb_object_keys(COALESCE(p_patch, '{}'::jsonb));
    IF changed_fields > 0 THEN
        UPDATE public.propiedades
        SET
            titulo = CASE WHEN p_patch ? 'titulo' THEN p_patch->>'titulo' ELSE current_row.titulo END,
            descripcion = CASE WHEN p_patch ? 'descripcion' THEN p_patch->>'descripcion' ELSE current_row.descripcion END,
            precio = CASE WHEN p_patch ? 'precio' THEN (p_patch->>'precio')::numeric ELSE current_row.precio END,
            moneda = CASE WHEN p_patch ? 'moneda' THEN p_patch->>'moneda' ELSE current_row.moneda END,
            tipo_propiedad = CASE WHEN p_patch ? 'tipo_propiedad' THEN p_patch->>'tipo_propiedad' ELSE current_row.tipo_propiedad END,
            operacion = CASE WHEN p_patch ? 'operacion' THEN p_patch->>'operacion' ELSE current_row.operacion END,
            ambientes = CASE WHEN p_patch ? 'ambientes' THEN (p_patch->>'ambientes')::integer ELSE current_row.ambientes END,
            dormitorios = CASE WHEN p_patch ? 'dormitorios' THEN (p_patch->>'dormitorios')::integer ELSE current_row.dormitorios END,
            banos = CASE WHEN p_patch ? 'banos' THEN (p_patch->>'banos')::integer ELSE current_row.banos END,
            superficie_total = CASE WHEN p_patch ? 'superficie_total' THEN (p_patch->>'superficie_total')::numeric ELSE current_row.superficie_total END,
            direccion = CASE WHEN p_patch ? 'direccion' THEN p_patch->>'direccion' ELSE current_row.direccion END,
            barrio = CASE WHEN p_patch ? 'barrio' THEN p_patch->>'barrio' ELSE current_row.barrio END,
            ciudad = CASE WHEN p_patch ? 'ciudad' THEN p_patch->>'ciudad' ELSE current_row.ciudad END,
            latitud = CASE WHEN p_patch ? 'latitud' THEN (p_patch->>'latitud')::double precision ELSE current_row.latitud END,
            longitud = CASE WHEN p_patch ? 'longitud' THEN (p_patch->>'longitud')::double precision ELSE current_row.longitud END,
            imagenes = CASE
                WHEN p_patch ? 'imagenes'
                THEN ARRAY(SELECT jsonb_array_elements_text(p_patch->'imagenes'))
                ELSE current_row.imagenes
            END,
            updated_at = now()
        WHERE id = current_row.id;
    END IF;

    audit_rows := public.record_property_merge_audit(
        current_row.id, p_source_id, p_run_id, p_audit
    );

    RETURN jsonb_build_object(
        'status', CASE WHEN changed_fields > 0 THEN 'updated' ELSE 'unchanged' END,
        'property_id', current_row.id,
        'changed_fields', changed_fields,
        'audit_rows', audit_rows
    );
END
$function$;

REVOKE EXECUTE ON FUNCTION public.record_property_merge_audit(bigint, text, text, jsonb)
    FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.insert_property_safe(jsonb, text, text, jsonb)
    FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.apply_property_safe_merge(
    bigint, bigint, text, text, text, jsonb, text, text, jsonb
) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_property_merge_audit(bigint, text, text, jsonb)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.insert_property_safe(jsonb, text, text, jsonb)
    TO service_role;
GRANT EXECUTE ON FUNCTION public.apply_property_safe_merge(
    bigint, bigint, text, text, text, jsonb, text, text, jsonb
) TO service_role;

DO $validate$
BEGIN
    IF has_table_privilege('anon', 'public.property_merge_audit', 'SELECT')
       OR has_table_privilege('authenticated', 'public.property_merge_audit', 'SELECT')
       OR has_function_privilege(
            'anon',
            'public.apply_property_safe_merge(bigint,bigint,text,text,text,jsonb,text,text,jsonb)',
            'EXECUTE'
       )
    THEN
        RAISE EXCEPTION 'merge audit object exposed to a public API role';
    END IF;
    IF NOT has_function_privilege(
        'service_role',
        'public.apply_property_safe_merge(bigint,bigint,text,text,text,jsonb,text,text,jsonb)',
        'EXECUTE'
    ) THEN
        RAISE EXCEPTION 'service_role cannot execute safe merge';
    END IF;
END
$validate$;

COMMIT;
