import type { SupabaseProperty } from "@/types/property";

export const completeRow: SupabaseProperty = {
  id: 123,
  inmobiliaria_id: 9,
  url: "https://inmobiliaria.example/propiedad/123",
  titulo: "Casa luminosa con jardín",
  descripcion: "Una descripción suficiente, provista por la publicación original.",
  precio: 180000,
  moneda: "USD",
  precio_usd: 180000,
  precio_ars: null,
  expensas: null,
  expensas_moneda: null,
  tipo_propiedad: "casa",
  operacion: "venta",
  ambientes: 4,
  dormitorios: 3,
  banos: 2,
  toilettes: 1,
  cocheras: 1,
  antiguedad: 8,
  piso: null,
  superficie_total: 240,
  superficie_cubierta: 170,
  superficie_terreno: 240,
  direccion: "Calle 123",
  barrio: "Centro",
  ciudad: "Córdoba",
  provincia: "Córdoba",
  pais: "Argentina",
  latitud: -31.42,
  longitud: -64.18,
  imagenes: ["https://images.example/house.jpg"],
  video_url: null,
  plano_url: null,
  amenities: ["Pileta", "Jardín"],
  agente_nombre: "María",
  agente_telefono: "3515555555",
  fuente_extraccion: "public",
  cms_origen: null,
  fecha_publicacion: "2026-07-20",
  estado: "activa",
  created_at: "2026-07-20T10:00:00Z",
  updated_at: "2026-07-25T10:00:00Z",
  apto_credito: true,
};

