import type { Property } from "@/types/property";

export const mockProperties: Property[] = [
  {
    id: "prop-palermo-chico-001",
    agencyId: "agency-inmocapital-select",
    sourceUrl: "https://inmocapital.local/propiedades/prop-palermo-chico-001",
    externalId: "IC-1001",
    dedupHash: "palermo-chico-285000-92",
    title: "Departamento premium con amenities",
    description:
      "Unidad luminosa en edificio de categoría con amenities, seguridad y excelente acceso a parques.",
    price: 285000,
    currency: "USD",
    priceUsd: 285000,
    priceArs: null,
    expenses: 180000,
    expensesCurrency: "ARS",
    propertyType: "departamento",
    operation: "venta",
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    toilettes: 1,
    garages: 1,
    age: 6,
    floor: 8,
    totalArea: 92,
    coveredArea: 86,
    landArea: null,
    address: "Av. Cerviño 3400",
    neighborhood: "Palermo Chico",
    city: "CABA",
    province: "Buenos Aires",
    country: "Argentina",
    latitude: -34.5808,
    longitude: -58.4072,
    images: [
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=900&q=80",
    ],
    hasRealImage: true,
    videoUrl: null,
    floorPlanUrl: null,
    amenities: ["Amenities", "Seguridad", "Pileta"],
    agencyName: "InmoCapital Select",
    agencyWeb: null,
    agencyPhone: null,
    agencyEmail: null,
    agentName: "Martina Ríos",
    agentPhone: "+54 9 11 5555-0101",
    extractionSource: "mock",
    originCms: "inmocapital",
    publishedAt: "2026-05-01T14:20:00.000Z",
    createdAt: "2026-05-01T14:20:00.000Z",
    updatedAt: "2026-05-08T12:00:00.000Z",
    status: "activa",
    mortgageEligible: true,
    badges: ["Destacado", "Amenities", "Cochera"],
  },
  {
    id: "prop-nordelta-agua-002",
    agencyId: "agency-inmocapital-norte",
    sourceUrl: "https://inmocapital.local/propiedades/prop-nordelta-agua-002",
    externalId: "IC-1002",
    dedupHash: "nordelta-casa-640000-620",
    title: "Casa al agua en barrio cerrado",
    description:
      "Casa moderna con jardín, galería y vista abierta al agua dentro de barrio privado consolidado.",
    price: 640000,
    currency: "USD",
    priceUsd: 640000,
    priceArs: null,
    expenses: 260000,
    expensesCurrency: "ARS",
    propertyType: "casa",
    operation: "venta",
    rooms: 5,
    bedrooms: 4,
    bathrooms: 4,
    toilettes: 1,
    garages: 2,
    age: 3,
    floor: null,
    totalArea: 620,
    coveredArea: 310,
    landArea: 620,
    address: "Barrio Los Lagos",
    neighborhood: "Nordelta",
    city: "Tigre",
    province: "Buenos Aires",
    country: "Argentina",
    latitude: -34.4009,
    longitude: -58.6498,
    images: [
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=900&q=80",
    ],
    hasRealImage: true,
    videoUrl: null,
    floorPlanUrl: null,
    amenities: ["Agua", "Barrio privado", "Jardín"],
    agencyName: "InmoCapital Norte",
    agencyWeb: null,
    agencyPhone: null,
    agencyEmail: null,
    agentName: "Lucas Ferreyra",
    agentPhone: "+54 9 11 5555-0102",
    extractionSource: "mock",
    originCms: "inmocapital",
    publishedAt: "2026-04-28T10:00:00.000Z",
    createdAt: "2026-04-28T10:00:00.000Z",
    updatedAt: "2026-05-07T16:30:00.000Z",
    status: "activa",
    mortgageEligible: false,
    badges: ["Destacado", "Agua", "Barrio privado"],
  },
  {
    id: "prop-mendoza-renta-003",
    agencyId: "agency-inmocapital-cuyo",
    sourceUrl: "https://inmocapital.local/propiedades/prop-mendoza-renta-003",
    externalId: "IC-1003",
    dedupHash: "mendoza-centro-138000-58",
    title: "Unidad para renta temporaria",
    description:
      "Departamento equipado cerca de zonas gastronómicas, ideal para renta turística y estadías ejecutivas.",
    price: 138000,
    currency: "USD",
    priceUsd: 138000,
    priceArs: null,
    expenses: 65000,
    expensesCurrency: "ARS",
    propertyType: "departamento",
    operation: "inversion",
    rooms: 2,
    bedrooms: 1,
    bathrooms: 1,
    toilettes: 0,
    garages: 0,
    age: 8,
    floor: 4,
    totalArea: 58,
    coveredArea: 54,
    landArea: null,
    address: "Chile 1200",
    neighborhood: "Centro",
    city: "Ciudad de Mendoza",
    province: "Mendoza",
    country: "Argentina",
    latitude: -32.8895,
    longitude: -68.8458,
    images: [
      "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=900&q=80",
    ],
    hasRealImage: true,
    videoUrl: null,
    floorPlanUrl: null,
    amenities: ["Amoblado", "Renta", "Luminoso"],
    agencyName: "InmoCapital Cuyo",
    agencyWeb: null,
    agencyPhone: null,
    agencyEmail: null,
    agentName: "Sofía Blanco",
    agentPhone: "+54 9 261 555-0103",
    extractionSource: "mock",
    originCms: "inmocapital",
    publishedAt: "2026-04-25T09:45:00.000Z",
    createdAt: "2026-04-25T09:45:00.000Z",
    updatedAt: "2026-05-06T10:15:00.000Z",
    status: "activa",
    mortgageEligible: true,
    badges: ["Destacado", "Renta", "Oportunidad"],
  },
  {
    id: "prop-belgrano-alquiler-004",
    agencyId: "agency-inmocapital-urbana",
    sourceUrl: "https://inmocapital.local/propiedades/prop-belgrano-alquiler-004",
    externalId: "IC-1004",
    dedupHash: "belgrano-alquiler-1450000-84",
    title: "Semipiso con balcón y cochera",
    description:
      "Semipiso en alquiler con balcón corrido, ambientes amplios y cochera fija en zona residencial.",
    price: 1450000,
    currency: "ARS",
    priceUsd: null,
    priceArs: 1450000,
    expenses: 210000,
    expensesCurrency: "ARS",
    propertyType: "departamento",
    operation: "alquiler",
    rooms: 3,
    bedrooms: 2,
    bathrooms: 2,
    toilettes: 0,
    garages: 1,
    age: 12,
    floor: 6,
    totalArea: 84,
    coveredArea: 78,
    landArea: null,
    address: "Mendoza 1800",
    neighborhood: "Belgrano",
    city: "CABA",
    province: "Buenos Aires",
    country: "Argentina",
    latitude: -34.5631,
    longitude: -58.4566,
    images: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=900&q=80",
    ],
    hasRealImage: true,
    videoUrl: null,
    floorPlanUrl: null,
    amenities: ["Balcón", "Cochera", "Encargado"],
    agencyName: "InmoCapital Urbana",
    agencyWeb: null,
    agencyPhone: null,
    agencyEmail: null,
    agentName: "Nicolás Peralta",
    agentPhone: "+54 9 11 5555-0104",
    extractionSource: "mock",
    originCms: "inmocapital",
    publishedAt: "2026-05-02T11:10:00.000Z",
    createdAt: "2026-05-02T11:10:00.000Z",
    updatedAt: "2026-05-08T18:05:00.000Z",
    status: "activa",
    mortgageEligible: false,
    badges: ["Destacado", "Nuevo", "Cochera"],
  },
];

export const featuredProperties = mockProperties.filter((property) =>
  property.badges.includes("Destacado"),
);
